# Generated by Django 5.2.8 on 2025-11-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solarHeater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('liters', models.IntegerField()),
                ('persons', models.IntegerField()),
                ('number_of_tubes', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
