# Generated by Django 5.2.8 on 2025-11-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarheater',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
