# Generated by Django 5.2.8 on 2025-11-22 00:43

import appTest.storage_backend
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0002_solarheater_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solarheater',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='solarheater',
            name='photo',
        ),
        migrations.AlterField(
            model_name='solarheater',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='solarheater',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='solarheater',
            name='liters',
            field=models.IntegerField(verbose_name='Litros'),
        ),
        migrations.AlterField(
            model_name='solarheater',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='solarheater',
            name='number_of_tubes',
            field=models.IntegerField(verbose_name='Numero de tubos'),
        ),
        migrations.AlterField(
            model_name='solarheater',
            name='persons',
            field=models.IntegerField(verbose_name='Personas'),
        ),
        migrations.AlterField(
            model_name='solarheater',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='solarHeaterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=appTest.storage_backend.ImageKitStorage, upload_to='', verbose_name='Imagen(es)')),
                ('heater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appTest.solarheater')),
            ],
        ),
    ]
