# Generated by Django 5.2.8 on 2025-11-23 03:09

import appTest.storage_backend
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0003_alter_solarheater_options_remove_solarheater_photo_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Producto')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL Amigable)')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
            },
        ),
        migrations.RemoveField(
            model_name='solarheaterimage',
            name='heater',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(storage=appTest.storage_backend.ImageKitStorage, upload_to='', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Campo')),
                ('field_slug', models.SlugField(max_length=100, verbose_name='Clave del Campo (JSON)')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='appTest.producttype', verbose_name='Tipo de Producto Asociado')),
            ],
            options={
                'verbose_name': 'Atributo de Producto',
                'verbose_name_plural': 'Atributos de Producto',
                'unique_together': {('product_type', 'field_slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('attributes', models.JSONField(default=dict, verbose_name='Atributos Específicos')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appTest.producttype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.DeleteModel(
            name='solarHeater',
        ),
        migrations.DeleteModel(
            name='solarHeaterImage',
        ),
    ]
