# Generated by Django 5.2.8 on 2025-11-23 03:20

import appTest.storage_backend
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0004_producttype_remove_solarheaterimage_heater_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='solarHeater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('liters', models.IntegerField(verbose_name='Litros')),
                ('persons', models.IntegerField(verbose_name='Personas')),
                ('number_of_tubes', models.IntegerField(verbose_name='Numero de tubos')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product_type',
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='order',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=appTest.storage_backend.ImageKitStorage, upload_to='', verbose_name='Imagen(es)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='heater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appTest.solarheater'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
