# Generated by Django 5.2.8 on 2025-11-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0005_solarheater_alter_productattribute_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solarheater',
            options={'verbose_name': 'Calentador', 'verbose_name_plural': 'Calentadores'},
        ),
    ]
