# Generated by Django 5.2.8 on 2025-11-23 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0006_alter_solarheater_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
            ],
        ),
        migrations.RemoveField(
            model_name='solarheater',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='solarheater',
            name='description',
        ),
        migrations.RemoveField(
            model_name='solarheater',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solarheater',
            name='name',
        ),
        migrations.RemoveField(
            model_name='solarheater',
            name='price',
        ),
        migrations.CreateModel(
            name='solarLight',
            fields=[
                ('base_model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appTest.base_model')),
                ('watts', models.IntegerField(verbose_name='Watts')),
                ('duration', models.IntegerField(verbose_name='Duracion')),
            ],
            options={
                'verbose_name': 'Lampara solar',
                'verbose_name_plural': 'Lamparas solares',
            },
            bases=('appTest.base_model',),
        ),
        migrations.AddField(
            model_name='solarheater',
            name='base_model_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appTest.base_model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='light',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appTest.solarlight'),
        ),
    ]
