# Generated by Django 5.2.8 on 2025-11-23 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0007_base_model_remove_solarheater_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='heater',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='light',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appTest.base_model'),
        ),
    ]
