# Generated by Django 5.2.8 on 2025-11-23 03:46

import appTest.storage_backend
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0008_remove_productimage_heater_remove_productimage_light_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=appTest.storage_backend.ImageKitStorage, upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appTest.base_model'),
        ),
    ]
