# Generated by Django 5.2.8 on 2025-11-24 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTest', '0009_alter_productimage_image_alter_productimage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='testProduct',
            fields=[
                ('base_model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appTest.base_model')),
                ('test', models.IntegerField(verbose_name='Test')),
                ('test2', models.EmailField(max_length=254, verbose_name='Email')),
                ('test3', models.DateField(verbose_name='Date')),
            ],
            bases=('appTest.base_model',),
        ),
    ]
